### ISSUE TITLE
ItemColor not found causing baconators to fail.

### ISSUE THREAD

**Issue by deathlynocturnal** [Bumblecat/Foodsicles#1] opened 2022-02-06 01:58 UTC
```
Mod File: baconators-1.18.1-4.0.4.jar
        Failure message: Baconators (baconators) has failed to load correctly
                java.lang.reflect.InvocationTargetException: null
        Mod Version: 1.18.1-4.0.4
        Mod Issue URL: https://bumblecat.dev/issues/foodsicles
        Exception message: java.lang.ClassNotFoundException: net.minecraft.client.color.item.ItemColor
Stacktrace:
        at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-1.0.1.jar:?] {}
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
        at dev.bumblecat.baconators.common.ObjectHolders.lambda$register$0(ObjectHolders.java:25) ~[baconators-1.18.1-4.0.4.jar%2345!/:1.18.1-4.0.4] {re:classloading,pl:object_holder_definalize:A}
        at dev.bumblecat.bumblecore.common.register.Registry.register(Registry.java:93) ~[bumblecore-1.18.1-1.0.3.jar%2349!/:1.18.1-1.0.3] {re:classloading}
        at dev.bumblecat.bumblecore.common.register.Registry.register(Registry.java:68) ~[bumblecore-1.18.1-1.0.3.jar%2349!/:1.18.1-1.0.3] {re:classloading}
        at dev.bumblecat.baconators.common.ObjectHolders.register(ObjectHolders.java:24) ~[baconators-1.18.1-4.0.4.jar%2345!/:1.18.1-4.0.4] {re:classloading,pl:object_holder_definalize:A}
        at dev.bumblecat.baconators.Baconators.<init>(Baconators.java:17) ~[baconators-1.18.1-4.0.4.jar%2345!/:1.18.1-4.0.4] {re:classloading}
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
        at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
        at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
        at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81) ~[javafmllanguage-1.18.1-39.0.66.jar%23131!/:?] {}
        at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[fmlcore-1.18.1-39.0.66.jar%23130!/:?] {}
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
        at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}
```

**Comment by Baijson** [comment] 2022-02-06 09:44
I'm not able to reproduce this error.

Did this happen on a newly created world? 
If not, what version of baconators/foodsicles/bumblecore did you have installed prior to updating to the newest versions? (I see you have bumblecore 1.0.3 installed)

**Comment by Baijson** [comment] 2022-02-06 10:21
build everything on a different machine and pushed updates to curseforge. see if this fixes it.

**Comment by Baijson** [comment] 2022-02-08 16:27
Closing this issue for now, as i'm assuming it is no longer a thing. Feel free however to re-open if it has not been solved.

**Closed as completed by Baijson** 2022-02-08 16:27 UTC
Labels: 1.18.x, bug
